---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tiktos/smmraja
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH && /usr/local/bin/php artisan config:cache
    - cd $DEPLOYPATH && /usr/local/bin/php artisan route:cache
    - cd $DEPLOYPATH && /usr/local/bin/php artisan view:cache
